language: python
sudo: false
branches:
only:
  - master
os:
  - linux

matrix:
  include:
    - env: ENV_FILE="ci/travis/35-minimal.yaml"
    - env: ENV_FILE="ci/travis/36.yaml"
    - env: ENV_FILE="ci/travis/37-latest-conda-forge.yaml"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda info
  - conda env create --file="${ENV_FILE}"
  - source activate test-environment
  - pip install coveralls

install:
  - python -m pip install -e .
  - conda list

script:
  - python setup.py sdist >/dev/null
  - python -m pytest -v tests/ --cov contextily

notifications:
    email:
        recipients:
            - daniel.arribas.bel@gmail.com
        on_failure: always

after_success:
    - coveralls
