name: contextily_docs
channels:
- conda-forge
dependencies:
- python=3.7
# dependencies
- numpy
- geopy
- matplotlib-base
- mercantile
- pillow
- rasterio
- requests
- xyzservices
# doc dependencies
- sphinx
- numpydoc
- nbsphinx
- pandoc
- ipython
- pip:
  - git+https://github.com/pandas-dev/pydata-sphinx-theme.git@master
